---
- name: Install required packages
  ansible.builtin.package:
    name: '{{ item }}'
    state: present
  loop:
    - unzip

- name: Create ownCloud install directory
  ansible.builtin.file:
    dest: '{{ oc_install_path }}'
    state: directory
    owner: apache
    group: apache
    mode: 0755
    recurse: yes

- name: Retrieve ownCloud and unarchive
  ansible.builtin.unarchive:
    src: '{{ oc_tarball_url }}'
    dest: '{{ oc_install_path }}'
    group: apache
    mode: 0755
    owner: apache
    remote_src: yes

- name: Copy "{{ oc_httpd_conf_confd }} to '/etc/httpd/conf.d/'"
  ansible.builtin.file:
    path: "/etc/httpd/conf.d/{{ oc_httpd_conf_confd }}"
    state: touch
    mode: 0644

- name: Restart httpd
  ansible.builtin.service:
    name: httpd
    state: restarted
    enabled: yes
