---
dependency:
  name: galaxy
driver:
  name: delegated
platforms:
  - name: owncloud
    image: ${MOLECULE_IMAGE}
    networks: molecule_owncloud
  - name: db
    image: mysql:5.7
    networks: molecule_owncloud
    env:
      mysql_root_password: someowncloud
      mysql_database: owncloud
      mysql_user: owncloud
      mysql_password: owncloud
  - name: selenium
    image: selenium/standalone-firefox:latest
    networks: molecule_owncloud
provisioner:
  name: ansible
  config_options:
    defaults:
      callbacks_enabled: ansible.posix.profile_tasks
  connection_options:
    php_packages:
      - php-curl
      - php-gd
      - php-intl
      - php-json
      - php-ldap
      - php-mbstring
      - php-mysqlnd
      - php-xml
      - php-zip
      - php-opcache
verifier:
  name: ansible
scenario:
  converge_sequence:
    - converge
  destroy_sequence:
    - destroy
  test_sequence:
    - dependency
    - syntax
    - create
    - converge
    - verify
    - destroy
